@echo off
TITLE React discovery Control Center
echo Starting the Structural Discovery Engine...
echo [Step 1] Activating Virtual Environment...
call .venv\Scripts\activate
echo [Step 2] Launching Dashboard...
streamlit run core_engine/demo_app.py
pause
